---

- name: Common tasks
  hosts: all
  become: yes
  become_method: sudo
  remote_user: ec2-user
  vars_files:
    - packages-list.yaml
  roles:
    - ansible-role-aws-tools
  tasks:
    - include_tasks: tasks/install-packages.yaml
    - include_tasks: tasks/oh_my_zsh.yaml