---

- name: Download oh my zsh installer
  get_url:
    url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
    dest: /tmp/install-oh-my-zsh.sh
    mode: 0777

- name: Install oh my zsh
  command: yes | bash /tmp/install-oh-my-zsh.sh