---

- name: Clone oh-my-zsh official project
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "/home/{{ ansible_ssh_user }}/.oh-my-zsh"
  sudo: no

- name: Creating new ~/.zshrc
  copy:
    src: "/home/{{ ansible_ssh_user }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "/home/{{ ansible_ssh_user }}/.zshrc"
  sudo: no